backend/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, :only => [:update]
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, :except => [:show] do
      member do
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, :except => [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', :to => 'admin/orders#index', :as => :admin
end

backend/app/controllers/spree/admin/payment_methods_controller.rb
module Spree
  module Admin
    class PaymentMethodsController < ResourceController
      skip_before_filter :load_resource, :only => [:create]
      before_filter :load_data
      before_filter :validate_payment_method_provider, :only => :create

      respond_to :html

      def create
        @payment_method = params[:payment_method].delete(:type).constantize.new(payment_method_params)
        @object = @payment_method
        invoke_callbacks(:create, :before)
        if @payment_method.save
          invoke_callbacks(:create, :after)
          flash[:success] = Spree.t(:successfully_created, :resource => Spree.t(:payment_method))
          redirect_to edit_admin_payment_method_path(@payment_method)
        else
          invoke_callbacks(:create, :fails)
          respond_with(@payment_method)
        end
      end

      def update
        invoke_callbacks(:update, :before)
        payment_method_type = params[:payment_method].delete(:type)
        if @payment_method['type'].to_s != payment_method_type
          @payment_method.update_columns(
            type: payment_method_type,
            updated_at: Time.now,
          )
          @payment_method = PaymentMethod.find(params[:id])
        end

        update_params = params[ActiveModel::Naming.param_key(@payment_method)] || {}
        attributes = payment_method_params.merge(update_params)
        attributes.each do |k,v|
          if k.include?("password") && attributes[k].blank?
            attributes.delete(k)
          end
        end

        if @payment_method.update_attributes(attributes)
          invoke_callbacks(:update, :after)
          flash[:success] = Spree.t(:successfully_updated, :resource => Spree.t(:payment_method))
          redirect_to edit_admin_payment_method_path(@payment_method)
        else
          invoke_callbacks(:update, :fails)
          respond_with(@payment_method)
        end
      end

      private

      def load_data
        @providers = Gateway.providers.sort{|p1, p2| p1.name <=> p2.name }
      end

      def validate_payment_method_provider
        valid_payment_methods = Rails.application.config.spree.payment_methods.map(&:to_s)
        if !valid_payment_methods.include?(params[:payment_method][:type])
          flash[:error] = Spree.t(:invalid_payment_provider)
          redirect_to new_admin_payment_method_path
        end
      end

      def payment_method_params
        params.require(:payment_method).permit!
      end
    end
  end
end

backend/app/views/spree/admin/payment_methods/_form.html.erb
<div data-hook="admin_payment_method_form_fields">

  <div data-hook="payment_method">

    <div class="alpha four columns">
      <div id="preference-settings" data-hook class="field">
        <%= f.label :type, Spree.t(:provider) %>
        <%= collection_select(:payment_method, :type, @providers, :to_s, :name, {}, {:id => 'gtwy-type', :class => 'select2 fullwidth'}) %>

        <% unless @object.new_record? %>
          <%= preference_fields(@object, f) %>

          <% if @object.respond_to?(:preferences) %>
            <div id="gateway-settings-warning" class="info warning"><%= Spree.t(:provider_settings_warning) %></div>
          <% end %>
        <% end %>
      </div>
      <div data-hook="environment" class="field">
        <%= label_tag nil, Spree.t(:environment) %>
        <%= collection_select(:payment_method, :environment, rails_environments, :to_s, :titleize, {}, {:id => 'gtwy-env', :class => 'select2 fullwidth'}) %>
      </div>
      <div data-hook="display" class="field">
        <%= label_tag nil, Spree.t(:display) %>
        <%= select(:payment_method, :display_on, Spree::PaymentMethod::DISPLAY.collect { |display| [Spree.t(display), display == :both ? nil : display.to_s] }, {}, {:class => 'select2 fullwidth'}) %>
      </div>
      <div data-hook="auto_capture" class="field">
        <%= label_tag nil, Spree.t(:auto_capture) %>
        <%= select(:payment_method, :auto_capture, [["#{Spree.t(:use_app_default)} (#{Spree::Config[:auto_capture]})", ''], [Spree.t(:say_yes), true], [Spree.t(:say_no), false]], {}, {:class => 'select2 fullwidth'}) %>
      </div>
      <div data-hook="active" class="field">
        <%= label_tag nil, Spree.t(:active) %>
        <ul>
          <li>
            <%= radio_button :payment_method, :active, true %>
            <%= label_tag nil, Spree.t(:say_yes) %>
          </li>
          <li>
            <%= radio_button :payment_method, :active, false %>
            <%= label_tag nil, Spree.t(:say_no) %>
          </li>
        </ul>
      </div>
    </div>

    <div class="omega eight columns">
      <div data-hook="name" class="field">
        <%= label_tag nil, Spree.t(:name) %>
        <%= text_field :payment_method, :name, :class => 'fullwidth' %>
      </div>
      <div data-hook="description" class="field">
        <%= label_tag nil, Spree.t(:description) %>
        <%= text_area :payment_method, :description, {:cols => 60, :rows => 6, :class => 'fullwidth'} %>
      </div>
    </div>

  </div>
</div>

<div class="clear"></div>

backend/app/views/spree/admin/payment_methods/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_payment_method) %> <i class="fa fa-arrow-right"></i> <%= @payment_method.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_payment_methods_list), spree.admin_payment_methods_path, :icon => 'arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @payment_method } %>

<%= form_for @payment_method, :url => admin_payment_method_path(@payment_method) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t('actions.update'), 'refresh' %>
    </div>
  </fieldset>

<% end %>

backend/app/views/spree/admin/payment_methods/index.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:payment_methods) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_payment_method), new_object_url, :icon => 'plus', :id => 'admin_new_payment_methods_link' %>
  </li>
<% end %>

<% if @payment_methods.any? %>
  <table class="index" id='listing_payment_methods'>
    <colgroup>
      <col style="width: 15%">
      <col style="width: 35%">
      <col style="width: 15%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_payment_methods_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:provider) %></th>
        <th><%= Spree.t(:environment) %></th>
        <th><%= Spree.t(:display) %></th>
        <th><%= Spree.t(:active) %></th>
        <th data-hook="admin_payment_methods_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @payment_methods.each do |method|%>
        <tr id="<%= spree_dom_id method %>" data-hook="admin_payment_methods_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= method.name %></td>
          <td class="align-center"><%= method.type %></td>
          <td class="align-center"><%= method.environment.to_s.titleize %></td>
          <td class="align-center"><%= method.display_on.blank? ? Spree.t(:both) : Spree.t(method.display_on) %></td>
          <td class="align-center"><%= method.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td data-hook="admin_payment_methods_index_row_actions" class="actions">
            <%= link_to_edit method, :no_text => true %>
            <%= link_to_delete method, :no_text => true  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/payment_method')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_payment_method_path %>!
  </div>
<% end %>

backend/app/views/spree/admin/payment_methods/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_payment_method) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_payment_methods_list), admin_payment_methods_path, :icon => 'arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @payment_method } %>

<%= form_for @payment_method, :url => collection_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'ok' %>
    </div>
  </fieldset>
<% end %>